version: '3'

services:
  php-fpm:
    image: php:8.2-fpm-alpine
    volumes:
      - ./:/var/www/app
    working_dir: /var/www/app

  nginx:
    image: nginx:mainline-alpine
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www/app
    ports:
      - "80:80"
    links:
      - php-fpm

#  app-db:
